name: Terraform Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_fmt:
    name: Check Terraform Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "TERRAFORM_VERSION=$(cat .terraform-version)"

      - name: Terraform Format Check
        id: fmt
        working-directory: ./modules
        run: terraform fmt -check --recursive

      - name: Fail if Terraform Format is Incorrect
        if: steps.fmt.outcome != 'success'
        run: |
          echo "Terraform format check failed. Please run 'terraform fmt' to format your code."
          exit 1
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform_fmt

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "TERRAFORM_VERSION=$(cat .terraform-version)"

      - name: Terraform Init
        working-directory: ./modules/main
        run: terraform init

      - name: Terraform Plan
        working-directory: ./modules/main
        run: terraform plan